# Generated by Django 6.1 on 2026-08-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado'), ('no_interesado', 'No interesado')], default='nuevo', max_length=30, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Observaciones administrativas')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Rehabilitación', 'Rehabilitación'), ('Mobiliario', 'Mobiliario')], max_length=60, verbose_name='Categoría')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Imagen principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Portafolio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(blank=True, verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Contenido general',
                'verbose_name_plural': 'Contenido general',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='portfolio/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Leyenda')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.portfolioproject', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen del proyecto',
                'verbose_name_plural': 'Imágenes del proyecto',
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
