# Generated by Django 6.1 on 2026-08-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='Ruta')),
                ('device_type', models.CharField(choices=[('mobile', 'Móvil'), ('tablet', 'Tablet'), ('pc', 'PC')], default='pc', max_length=20, verbose_name='Tipo de dispositivo')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visita')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-created_at'],
            },
        ),
    ]
