# Generated by Django 6.1 on 2026-08-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfoliocategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Imagen del proyecto', 'verbose_name_plural': 'Imágenes del proyecto'},
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
