# Generated by Django 6.1 on 2026-08-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_portfolioimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/optimized/', verbose_name='Imagen optimizada'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/thumbs/', verbose_name='Miniatura'),
        ),
    ]
